- name: Install and setup cart service
  become: yes  # Run all tasks as sudo/root
  hosts: cart  # Target is the cart machine

  tasks:

    # TASK 1: Disable the default Node.js module
    - name: Disable default Node.js module
      ansible.builtin.shell: dnf module disable nodejs -y

    # TASK 2: Enable Node.js 20 version
    - name: Enable Node.js 20 module
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    # TASK 3: Install Node.js from enabled module
    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present  # Install if not already installed

    # TASK 4: Create 'roboshop' user to run the application
    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop

    # TASK 5: Create application directory /app
    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'  # Set directory permissions

    # TASK 6: Download the cart source code zip file
    - name: Download cart zip file
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp/cart.zip

    # TASK 7: Extract the zip file into /app
    - name: Unarchive cart code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes  # File is present on control node (localhost--No, remote yes)

    # TASK 8: Run npm install inside /app to install dependencies
    - name: Run npm install in /app
      ansible.builtin.shell: npm install
      args:
        chdir: /app  # Run the command inside /app directory

    # TASK 9: Copy the systemd service file to the correct location
    - name: Copy cart service file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
        remote_src: no

    # TASK 10: Reload systemd daemon so it picks up new service
    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    # TASK 11: Start and enable the cart service
    - name: Start and enable cart service
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes

